neofs-adm: use registerTLD to register TLD
It's the only way since neofs-contract 0.18.0, "register" just fails with

    Error: could not perform test invocation: script failed (FAULT state) due to an error: at instruction 1794 (THROW): unhandled exception: "TLD denied"

Signed-off-by: Roman Khimov <roman@nspcc.ru>