sn/object: Fix EC GET with all data parts missing
For EC policies D/P with D <= P, object remains available when all data
parts are not. However, previously SN responded with incorrect (empty)
object in this case. In particular, CLI result was:
```
Error: rpc error: read header: missing object ID field in the response
```

Bug was caused by a logical error in the code. This fixes it.

Signed-off-by: Leonard Liubich <leonard@morphbits.io>