acl: drop unused unmarshalPublicKey
Linter:
  Error: func `unmarshalPublicKey` is unused (unused)
  Error: func `unmarshalPublicKey` is unused (unused)

Signed-off-by: Roman Khimov <roman@nspcc.ru>