*: don't use min/max for vars
They're special since Go 1.22, so linter isn't happy about their use:

  Error: param min has same name as predeclared identifier (predeclared)
  Error: param max has same name as predeclared identifier (predeclared)
  Error: variable min has same name as predeclared identifier (predeclared)
  Error: variable max has same name as predeclared identifier (predeclared)

Signed-off-by: Roman Khimov <roman@nspcc.ru>