cli: Use `MarkFlagsOneRequired` for mutex but required flags
The feature came with github.com/spf13/cobra@v1.8.0. We don't need to do
manual checks with it. For example, following command result changed
from:
```
$ neofs-cli bearer create -i 1 -n 2 --out b -o c
expiration epoch or lifetime period is required
```
to
```
Error: at least one of the flags in the group [expire-at lifetime] is required
```

Ret code remains = 1. Below are command checklists.
CLI:
 * `bearer create`;
 * `control shards evacuate`;
 * `control shards flush-cache`;
 * `control shards set-mode`;
 * `object lock`;
 * `session create`;
 * `storagegroup put`.
ADM:
 * `morph verified-nodes-domain set-access-list`;
 * `morph refill-gas`.

Closes #2595.

Signed-off-by: Leonard Lyubich <leonard@morphbits.io>